Repository vapor/leaf-kit, pull requests merged in 2020-03, with the labels that each got.

#32 Release Candidate 1
  .github/workflows/test.yml
  Package.swift
  README.md
Labels: enhancement

#28 Fix #if Conditional Logix
  Sources/LeafKit/LeafSerializer.swift
  Sources/LeafKit/ParameterResolver.swift
  Tests/LeafKitTests/LeafTests.swift
Labels: enhancement, semver-minor

#34 User info, tag config, and files protocol
  Sources/LeafKit/Deprecated.swift
  Sources/LeafKit/LeafRenderer.swift
  Sources/LeafKit/LeafSerializer.swift
  Sources/LeafKit/ParameterResolver.swift
  Tests/LeafKitTests/LeafKitTests.swift
  Tests/LeafKitTests/LeafTests.swift
Labels: enhancement, semver-minor

#37 Add requirement methods to LeafContext
  Sources/LeafKit/LeafRenderer.swift
Labels: enhancement, semver-minor

#41 Add Underscore as Valid in Parameter
  Sources/LeafKit/Exports.swift
  Sources/LeafKit/LeafLexer.swift
  Tests/LeafKitTests/LeafKitTests.swift
Labels: bug, semver-patch
